### ISSUE TITLE
Errors while installing osbjs

### ISSUE THREAD

**Issue by ohm002** [osbjs/osbjs#1]
Where the error occurs on the log ([Full log file](https://pastebin.com/5jySAgDm))
```log
...
528 info run canvas@2.8.0 install node_modules/canvas node-pre-gyp install --fallback-to-build
529 info run canvas@2.8.0 install { code: 1, signal: null }
530 timing reify:rollback:createSparse Completed in 932ms
531 timing reify:rollback:retireShallow Completed in 0ms
532 timing command:i Completed in 20798ms
533 verbose stack Error: command failed
533 verbose stack     at ChildProcess.<anonymous> (C:\Users\ohm\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
533 verbose stack     at ChildProcess.emit (node:events:390:28)
533 verbose stack     at maybeClose (node:internal/child_process:1062:16)
533 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
534 verbose pkgid canvas@2.8.0
535 verbose cwd C:\Users\ohm\Documents\GitHub\osbjs-codes
536 verbose Windows_NT 10.0.19042
537 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ohm\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "@osbjs/osbjs"
538 verbose node v17.0.1
539 verbose npm  v8.1.3
540 error code 1
541 error path C:\Users\ohm\Documents\GitHub\osbjs-codes\node_modules\canvas
542 error command failed
543 error command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
544 error Warning: Missing input files:
544 error C:\GTK\bin\libintl-8.dll
544 error C:\GTK\bin\libpangoft2-1.0-0.dll
544 error C:\GTK\bin\zlib1.dll
544 error C:\GTK\bin\libcairo-2.dll
544 error C:\GTK\bin\libgthread-2.0-0.dll
544 error C:\GTK\bin\libpangocairo-1.0-0.dll
544 error C:\GTK\bin\libpng14-14.dll
544 error C:\GTK\bin\libglib-2.0-0.dll
544 error C:\GTK\bin\libgobject-2.0-0.dll
544 error C:\GTK\bin\libpangowin32-1.0-0.dll
544 error C:\GTK\bin\libpango-1.0-0.dll
544 error C:\GTK\bin\libfontconfig-1.dll
544 error C:\GTK\bin\libgmodule-2.0-0.dll
544 error C:\GTK\bin\libexpat-1.dll
544 error C:\GTK\bin\libfreetype-6.dll
544 error Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
544 error   Backend.cc
544 error C:\Users\ohm\Documents\GitHub\osbjs-codes\node_modules\canvas\src\backend\Backend.h(3,10): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory [C:\Users\ohm\Documents\GitHub\osbjs-codes\node_modules\canvas\build\canvas.vcxproj]
544 error Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\ohm\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\ohm\Documents\GitHub\osbjs-codes\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\ohm\Documents\GitHub\osbjs-codes\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102' (1)
545 error node-pre-gyp info it worked if it ends with ok
545 error node-pre-gyp info using node-pre-gyp@1.0.6
545 error node-pre-gyp info using node@17.0.1 | win32 | x64
545 error node-pre-gyp info check checked for "C:\Users\ohm\Documents\GitHub\osbjs-codes\node_modules\canvas\build\Release\canvas.node" (not found)
545 error node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v102-win32-unknown-x64.tar.gz
545 error node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v102-win32-unknown-x64.tar.gz
545 error node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@17.0.1 (node-v102 ABI, unknown) (falling back to source compile with node-gyp)
545 error node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v102-win32-unknown-x64.tar.gz
545 error gyp info it worked if it ends with ok
545 error gyp info using node-gyp@8.3.0
545 error gyp info using node@17.0.1 | win32 | x64
545 error gyp info ok
545 error gyp info it worked if it ends with ok
545 error gyp info using node-gyp@8.3.0
545 error gyp info using node@17.0.1 | win32 | x64
545 error gyp info find Python using Python version 3.9.7 found at "C:\Users\ohm\AppData\Local\Programs\Python\Python39\python.exe"
545 error gyp info find VS using VS2019 (16.11.31729.503) found at:
545 error gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
545 error gyp info find VS run with --verbose for detailed information
545 error gyp info spawn C:\Users\ohm\AppData\Local\Programs\Python\Python39\python.exe
545 error gyp info spawn args [
545 error gyp info spawn args   'C:\\Users\\ohm\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
545 error gyp info spawn args   'binding.gyp',
545 error gyp info spawn args   '-f',
545 error gyp info spawn args   'msvs',
545 error gyp info spawn args   '-I',
545 error gyp info spawn args   'C:\\Users\\ohm\\Documents\\GitHub\\osbjs-codes\\node_modules\\canvas\\build\\config.gypi',
545 error gyp info spawn args   '-I',
545 error gyp info spawn args   'C:\\Users\\ohm\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
545 error gyp info spawn args   '-I',
545 error gyp info spawn args   'C:\\Users\\ohm\\AppData\\Local\\node-gyp\\Cache\\17.0.1\\include\\node\\common.gypi',
545 error gyp info spawn args   '-Dlibrary=shared_library',
545 error gyp info spawn args   '-Dvisibility=default',
545 error gyp info spawn args   '-Dnode_root_dir=C:\\Users\\ohm\\AppData\\Local\\node-gyp\\Cache\\17.0.1',
545 error gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\ohm\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
545 error gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\ohm\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\17.0.1\\\\<(target_arch)\\\\node.lib',
545 error gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\ohm\\Documents\\GitHub\\osbjs-codes\\node_modules\\canvas',
545 error gyp info spawn args   '-Dnode_engine=v8',
545 error gyp info spawn args   '--depth=.',
545 error gyp info spawn args   '--no-parallel',
545 error gyp info spawn args   '--generator-output',
545 error gyp info spawn args   'C:\\Users\\ohm\\Documents\\GitHub\\osbjs-codes\\node_modules\\canvas\\build',
545 error gyp info spawn args   '-Goutput_dir=.'
545 error gyp info spawn args ]
545 error gyp info ok
545 error gyp info it worked if it ends with ok
545 error gyp info using node-gyp@8.3.0
545 error gyp info using node@17.0.1 | win32 | x64
545 error gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
545 error gyp info spawn args [
545 error gyp info spawn args   'build/binding.sln',
545 error gyp info spawn args   '/clp:Verbosity=minimal',
545 error gyp info spawn args   '/nologo',
545 error gyp info spawn args   '/p:Configuration=Release;Platform=x64'
545 error gyp info spawn args ]
545 error gyp ERR! build error
545 error gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
545 error gyp ERR! stack     at ChildProcess.onExit (C:\Users\ohm\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
545 error gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
545 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
545 error gyp ERR! System Windows_NT 10.0.19042
545 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ohm\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\ohm\\Documents\\GitHub\\osbjs-codes\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\Users\\ohm\\Documents\\GitHub\\osbjs-codes\\node_modules\\canvas\\build\\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v102"
545 error gyp ERR! cwd C:\Users\ohm\Documents\GitHub\osbjs-codes\node_modules\canvas
545 error gyp ERR! node -v v17.0.1
545 error gyp ERR! node-gyp -v v8.3.0
545 error gyp ERR! not ok
545 error node-pre-gyp ERR! build error
545 error node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\ohm\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\ohm\Documents\GitHub\osbjs-codes\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\ohm\Documents\GitHub\osbjs-codes\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102' (1)
545 error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\ohm\Documents\GitHub\osbjs-codes\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
545 error node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
545 error node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1062:16)
545 error node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
545 error node-pre-gyp ERR! System Windows_NT 10.0.19042
545 error node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ohm\\Documents\\GitHub\\osbjs-codes\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
545 error node-pre-gyp ERR! cwd C:\Users\ohm\Documents\GitHub\osbjs-codes\node_modules\canvas
545 error node-pre-gyp ERR! node -v v17.0.1
545 error node-pre-gyp ERR! node-pre-gyp -v v1.0.6
545 error node-pre-gyp ERR! not ok
546 verbose exit 1
```

**Comment by ohm002** [comment]
oh looks like i have to install the cli manually first before installing the main one

**Comment by ohm002** [comment]
ok nvm its still having bugs when doing the sb. didnt save the logs but it shows something like
cannot use import statement outside a module on the first line of the example code 
```js
import { Storyboard, Sprite, Easing, Position, Origin, Layer } from '@osbjs/osbjs';

// Create storyboard instance
// If `path` is not specified, osbjs will create a new `storyboard` folder and save the storyboard there.
const sb = new Storyboard('Taishi feat. Hatsune Miku (Eng ver) - Scaler (Smug Nanachi).osb');

// Create a sprite
let sprite1 = new Sprite('sb/test.png', Layer.Background)
sprite1.Move(1000, 3000, new Position(320, 345), new Position(240, 480))

let sprite2 = new Sprite('sb/beam.png', Layer.Background)
sprite2.Fade(1, 1, 1, 0)

// Create a scene
let scene = new Scene()

// Add sprite to scene
scene.registerComponents(sprite)

// Register scene
sb.registerComponents(scene);

// Generate
sb.generate();
```
and when trying to install cli and this again it doesnt work anymore ur so  the

**Comment by nanachi-code** [comment]
you have to set type: 'module' in package.json to be able to use import statement
